run:
  allow-parallel-runners: true

linters:
  disable-all: true
  enable:
    - copyloopvar
    - dupl
    - errcheck
    - ginkgolinter
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused

linters-settings:
  revive:
    rules:
      - name: comment-spacings
      - name: import-shadowing
  lll:
    line-length: 120

issues:
  exclude-rules:
    - path: internal/webhook/
      linters:
        - lll
    - path: internal/rbac/
      linters:
        - lll
    - path: internal/controller/
      linters:
        - lll
    - path: _test\.go
      linters:
        - dupl
        - lll
