---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-rbac-kubevirt-io-v1alpha1-foldertree
  failurePolicy: Fail
  name: vfoldertree-v1alpha1.kb.io
  rules:
  - apiGroups:
    - rbac.kubevirt.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - foldertrees
  sideEffects: None
